# Setup
title:        Guilherme Blog
tagline:      Blog of Guilherme
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Guilherme
  url:        http://guilhermehas.github.io

# Collections
collections:
  items:
    output: true

# Gems
gems:
  - jekyll-paginate

#Others
permalink: /:title/
markdown: kramdown